### ISSUE TITLE
Error while building the Go files.

### ISSUE THREAD

**Issue by mouleshgs** [ChausseBenjamin/vimlogo-ansi#1]
after running the command, `go build -o vimlogo-ansi *.go` I am getting,
```shell
# command-line-arguments
./main.go:81:18: cannot range over p.width (variable of type uint32)
``` 
what to do?

**Comment by ChausseBenjamin** [comment]
What version of Go are you currently running? (you can get that info with `go version`)
As a temporary fix you could change line 81 in `main.go` to the following:
``` go
		for i := uint32(0); i < p.width; i++ {
```

**Comment by mouleshgs** [comment]
```shell
~/vimlogo-ansi $ go version
go version go1.18.1 linux/amd64
``` 

it works after changing the line!

**Comment by ChausseBenjamin** [comment]
As a note for others who might stumble onto this, it appears the syntax used in the main branch was introduced in Go 1.22:
https://go.dev/blog/go1.22
So updating to that version would also do the trick
